### ISSUE TITLE
Targets lost on merge

### ISSUE THREAD

**Issue by mmkumaran** [martinroob/ngx-i18nsupport#114] opened 2018-11-18 10:51 UTC
Just started using formatting tools for formatting angular templates, it started putting some translated text into new line.

I am formatting our template like this.

**_From :_**
``` 
<a  class="read-more-button"   id="show-more-overview"  i18n="Button to expand the study desctiption@@study-overview:read-more-button">???Read all </a>
```
**_To:_**
```
<a
          class="read-more-button"
          id="show-more-overview"
          i18n="Button to expand the study desctiption@@study-overview:read-more-button">
          ???Read all
 </a>
```
Following this change, I regenerated the translation file and merged to the the existing one.  Now every time i make a change to the template and run the merge it is losing all the changes that has translations in new line ex: for this one **_???Read all_**

I think the targets are lost if the actual source has the text in different lines/new line

example: 
Step1: generate the translation file
```
<source>
          ???Read all
</source>
<target state="final">
          ???Read all
</target>
```
Step2: : update the translation
```
<source>
          ???Read all
</source>
<target state="final">
          translated text
</target>
```

Step3: : update the angular template(just add new elements) and run extract and merge command(```ng xi18n && xliffmerge --profile xliffmerge.json en```). Text translated in step 2 are lost and switches back to ```???Read all``` instead of `translated text`
```
<source>
          ???Read all
</source>
<target state="final">
          ???Read all
</target>
```

Versions:
Angular : 6.1.2
ngx-i18nsupport: 0.17.0 (tried 0.17.1 as well)
xliffmerge.json settings
```
{
  "xliffmergeOptions": {
    "srcDir": "src/locale",
    "genDir": "src/locale",
    "beautifyOutput": true
  }
}
```

**Comment by martinroob** [comment] 2018-11-21 06:04
Hi,
Thanks for your feedback.
The behaviour you describe is intended.
en is the default language that you are using in your template. xliffmerge always keeps the translation file for the default language in sync with the text used in the templates.
So, every translation will be deleted.
For the scenario you want to have you must use a second language.

**Comment by mmkumaran** [comment] 2018-11-22 22:49
strange, it keeps all other translations which are in single line. only translations on new line are lost. 

```<source>???Read all</source>``` - this is kept as it is(no loss) and if the sources are in below format they are lost.

```
<source>
???Real all
</source>
```

I tried with second language and i see the same behaviour

**Comment by martinroob** [comment] 2018-11-23 07:32
OK, I will check soon.

**Comment by martinroob** [comment] 2019-01-11 13:55
Sorry, cannot reproduce it.
I tried exactly what you described.
Translation of "???Read all" is never touched.
For me everything works as expected.
So I will close this issue.

**Closed by martinroob** 2019-01-11 13:55 UTC
